"""Graphflow IR - Graph definitions.

Data structures representing the application execution graph (DAG, loops,
branches, parallel steps, human-in-the-loop interruptions, agents, nested
workflows), without depending on LangGraph.

Lowered IR (what ``Workflow.to_ir()`` returns and the compiler consumes) is
plain data: code and other live objects are registry reference strings (see
``graphflow.ir.registry``), so ``GraphIR.to_dict()`` is JSON-serializable.
Builder code may temporarily store callables in the ``condition`` /
``partition_fn`` fields; lowering replaces them with references.
"""

from __future__ import annotations

import dataclasses
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any, Literal

from graphflow.ir.agent import AgentIR
from graphflow.ir.registry import Registry
from graphflow.ir.retry import RetryIR
from graphflow.ir.state import StateSchemaIR

# Sentinel target meaning "terminate this path". Matches LangGraph's END value.
END = "__end__"

# Node ids with this prefix are generated by the compiler and hidden from users.
RESERVED_PREFIX = "__"

NodeKind = Literal["function", "raw", "agent", "subgraph"]
ErrorHandler = Callable[..., Any]
CallableRef = str | Callable[..., Any]  # a registry ref (lowered) or the callable (builder stage)


@dataclass
class NodeIR:
    """An executable node in the workflow graph."""
    id: str
    name: str
    kind: NodeKind = "function"
    target: str | None = None         # registry ref of the function (function / raw kinds)
    agent: AgentIR | None = None      # agent kind
    subgraph: GraphIR | None = None   # subgraph kind (embedded workflow)
    retries: int = 0                  # legacy: extra attempts on any error (see `retry`)
    retry: RetryIR | None = None      # retry policy; takes the place of `retries`
    timeout_seconds: float | None = None
    on_error: str | None = None       # registry ref of (state, error) -> update, used after retries
    isolate_errors: bool = False      # record failures in the `errors` state field instead of failing
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def is_agent(self) -> bool:
        return self.kind == "agent"

    @property
    def is_raw_langgraph(self) -> bool:
        return self.kind == "raw"


@dataclass
class EdgeIR:
    """A direct, deterministic transition between two nodes."""
    source: str
    target: str


@dataclass
class ConditionalEdgeIR:
    """A dynamic branch: `condition(state)` returns a key of `route_map`."""
    source: str
    condition: CallableRef
    route_map: dict[str, str] = field(default_factory=dict)  # result_key -> target_node_id
    is_dynamic_send: bool = False


@dataclass
class ParallelBranchIR:
    """A set of nodes executed concurrently, optionally joined by a fan-in node."""
    id: str
    source: str
    branch_nodes: list[str]
    fan_in: str = ""  # Node that runs once, after *all* branches complete


@dataclass
class DynamicFanOutIR:
    """Dynamic map-reduce / fan-out (spawning parallel workers per item)."""
    id: str
    source: str
    partition_fn: CallableRef
    worker_node: str
    fan_in: str


@dataclass
class LoopIR:
    """An iterative cycle: body runs, then repeats while `condition` holds.

    The body runs at most `max_iterations` times; afterwards control moves to
    `exit_node` (or END) even if the condition still holds.
    """
    id: str
    body_node: str
    condition: CallableRef
    exit_node: str = ""
    max_iterations: int = 25


@dataclass
class HITLIR:
    """A Human-In-The-Loop interruption point."""
    node_id: str
    prompt: str = "Human approval required"
    description: str = ""
    resume_target: str | None = None  # Node that runs after approval
    reject_target: str | None = None  # Node that runs after rejection; None = fail the run


@dataclass
class GraphIR:
    """The complete Intermediate Representation of an application graph."""
    name: str
    nodes: dict[str, NodeIR] = field(default_factory=dict)
    edges: list[EdgeIR] = field(default_factory=list)
    conditional_edges: list[ConditionalEdgeIR] = field(default_factory=list)
    parallel_branches: list[ParallelBranchIR] = field(default_factory=list)
    dynamic_fan_outs: list[DynamicFanOutIR] = field(default_factory=list)
    loops: list[LoopIR] = field(default_factory=list)
    hitl_nodes: dict[str, HITLIR] = field(default_factory=dict)
    entry_point: str | None = None
    state_schema: StateSchemaIR = field(default_factory=StateSchemaIR)
    error_handler: str | None = None  # registry ref of the workflow-wide fallback
    metadata: dict[str, Any] = field(default_factory=dict)

    def add_node(self, node: NodeIR) -> None:
        self.nodes[node.id] = node

    def add_edge(self, source: str, target: str) -> None:
        self.edges.append(EdgeIR(source=source, target=target))

    def all_node_ids(self) -> set[str]:
        return set(self.nodes) | set(self.hitl_nodes)

    def to_dict(self) -> dict[str, Any]:
        """A plain-dict (JSON-serializable, for lowered IR) representation."""
        return _drop_builder_fields(dataclasses.asdict(self))


def _drop_builder_fields(data: dict[str, Any]) -> dict[str, Any]:
    data["state_schema"].pop("raw_cls", None)
    for f in data["state_schema"]["fields"].values():
        f.pop("type_annotation", None)
    for node in data["nodes"].values():
        if node.get("subgraph") is not None:
            node["subgraph"] = _drop_builder_fields(node["subgraph"])
    return data


@dataclass
class LoweredWorkflow:
    """A lowered workflow: pure-data IR plus the registry its references point into."""
    ir: GraphIR
    registry: Registry
